name: The Fair Photographer
favicon: null
layout_spectrum: 0.5071245
typography_spectrum: 0.4298256
title: The Fair Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7151762
  lightness: 0.5022775
  saturation: 0.07623574
  rhythmicContrast: 0.1764547
purpose: []
