layout_spectrum: 0.5071245
typography_spectrum: 0.4298256
color:
  saturation: 0.07623574
  lightness: 0.5022775
  brandStrength: 0.7151762
  rhythmicContrast: 0.1764547
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: The Fair Photographer
