name: The Fair Photographer
favicon: null
layout_spectrum: 0.5071245
typography_spectrum: 0.4298256
title: The Fair Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdd3a9'
    - '#000000'
    - '#373533'
    - '#9a8b80'
    - '#64574b'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
